steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/onyx-glider-337908/testing', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/onyx-glider-337908/testing']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/onyx-glider-337908/testing:latest']